# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
      
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
        
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
        
    - name: Restore NuGet Packages
      run: nuget restore BankAccount.sln
      
      # Compile app in release mode
    - name: Build App
      run: msbuild BankAccount.sln /p:Configuration=Release
    
    - name: Set up VSTest
      uses: Malcolmnixon/Setup-VSTest@v2
    
    - name: Run VSTest
      run: vstest.console BankAccountTests\bin\Release\BankAccountTests.dll
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: BankAccountApp
        path: BankAccount\bin\Release
